
classes = '''{
            "firstLevelCategoryList":[
                {
                    "id":"6bumiplsplsTODCneDweUyunlrg==",
                    "name":"消化系统及代谢药",
                    "position":0,
                    "icon":"1_category_stomach"
                },
                {
                    "id":"zI5fplsplsBNzTCSKBdEwD2whEg==",
                    "name":"血液和造血系统药物",
                    "position":0,
                    "icon":"2_category_blood"
                },
                {
                    "id":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "name":"心血管系统药物",
                    "position":0,
                    "icon":"3_category_heart"
                },
                {
                    "id":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "name":"皮肤病用药",
                    "position":0,
                    "icon":"4_category_skin"
                },
                {
                    "id":"wLgjZt8jKiufR4H8LRQqyQ==",
                    "name":"生殖泌尿系统和性激素类药物",
                    "position":0,
                    "icon":"5_category_urinary"
                },
                {
                    "id":"jF8FzxOFsBpeYZuffcdTQw==",
                    "name":"全身用激素类制剂(不含性激素)",
                    "position":0,
                    "icon":"6_category_hormone"
                },
                {
                    "id":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "name":"全身用抗感染药物",
                    "position":0,
                    "icon":"7_category_infection"
                },
                {
                    "id":"oPYmepepmBOFKajCMeszxf2CnLA==",
                    "name":"抗肿瘤和免疫调节剂",
                    "position":0,
                    "icon":"8_category_tumor"
                },
                {
                    "id":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "name":"肌肉-骨骼系统",
                    "position":0,
                    "icon":"9_category_bone"
                },
                {
                    "id":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "name":"神经系统药物",
                    "position":0,
                    "icon":"10_category_nerve"
                },
                {
                    "id":"N5OXRZbGzWRAK7BdPwsaWw==",
                    "name":"抗寄生虫药、杀虫剂和驱虫剂",
                    "position":0,
                    "icon":"11_category_parasite"
                },
                {
                    "id":"Z6gvDdWkMY3JCRh554wMAA==",
                    "name":"呼吸系统用药",
                    "position":0,
                    "icon":"12_category_breath"
                },
                {
                    "id":"44ORHNfUVssuau8plsplsS0qVFw==",
                    "name":"感觉系统药物",
                    "position":0,
                    "icon":"13_category_feel"
                },
                {
                    "id":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "name":"杂类",
                    "position":0,
                    "icon":"14_category_others"
                },
                {
                    "id":"t4HJm6G8SjX73olgti6D7A==",
                    "name":"原料药及非直接作用于人体药物",
                    "position":0,
                    "icon":null
                }
            ],
            "secondLevelCategoryList":[
                {
                    "id":"6FO9JRKee7oGjg4ueqcElw==",
                    "name":"口腔科用药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"LBKmepepmkzC2NRXJUk2JPYRcfA==",
                            "drugName":"美克威"
                        },
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        }
                    ]
                },
                {
                    "id":"JLkCyHOcdV5zDGyxi2X1lw==",
                    "name":"抗酸药及治疗消化性溃疡和胃肠胀气用药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"u6fGlKhQ4ilZ4M7oZETDZw==",
                            "drugName":"丽奥佳"
                        }
                    ]
                },
                {
                    "id":"cPqgw0TA2P9mepepm2AYcddEYMw==",
                    "name":"胃肠解痉药，抗胆碱药和胃动力药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"IK2NxMTplsplsus7YBvge7ym0bQ==",
                            "drugName":"胃复安针"
                        }
                    ]
                },
                {
                    "id":"rnGcSVmepepmhabd6OspEy87GjA==",
                    "name":"止吐药和止恶心药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"CPf2amNPxNPpLPjLMtR7eQ==",
                            "drugName":"欧贝"
                        }
                    ]
                },
                {
                    "id":"bFxOMNuFdQ69EkDmLplsplsdrqw==",
                    "name":"胆、肝疾病治疗药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"Nli8GnARVKg37kk4L3Bwmepepmg==",
                            "drugName":"易善复"
                        },
                        {
                            "drugId":"ZC3TFpy6JWF0xsQswIUJCA==",
                            "drugName":"优思弗"
                        }
                    ]
                },
                {
                    "id":"rOqZfkENE7eplsplsIegTTUXFLQ==",
                    "name":"泻药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"MnkzprmepepmmBi580DOBoRKC3A==",
                    "name":"止泻药，肠道抗炎/抗感染药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"kMurWJRsdY0UbQsZWHARMg==",
                            "drugName":"稳可信"
                        },
                        {
                            "drugId":"iC6UplsplsXxNRePI5NOk5pECNA==",
                            "drugName":"易蒙停"
                        },
                        {
                            "drugId":"tIsBLdHqHboMLK3plsplsOjMdeA==",
                            "drugName":"希捷"
                        },
                        {
                            "drugId":"aOsovsqyUFiCimepepm1vbmepepmHRDA==",
                            "drugName":"吸入用布地奈德混悬液"
                        }
                    ]
                },
                {
                    "id":"O74klTiwAWvKmPAIs8ZdEg==",
                    "name":"抗肥胖病药，不包括饮食制品",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"TLsRp8zeXSnIG7FaIQFSwA==",
                    "name":"消化药，包括酶制剂",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"FUM9sasISqSIVvC99SzotA==",
                    "name":"糖尿病用药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"xQplaKCQmepepm4LUVuTAZqGbXw==",
                            "drugName":"诺和锐30笔芯"
                        },
                        {
                            "drugId":"NsNcs3ep25NSVi5yWvrH7Q==",
                            "drugName":"格华止"
                        },
                        {
                            "drugId":"GD9yyYplsplsmepepm1fK0ZcfMtyewTQ==",
                            "drugName":"盐酸二甲双胍缓释片(圣邦杰) "
                        }
                    ]
                },
                {
                    "id":"51HBpYMry0vukr0EPplsplsACfw==",
                    "name":"维生素类",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"GOfJHwqmepepmAkLaTIPOmepepmZ9uyA==",
                    "name":"矿物质补充剂",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"QjF4VbTDF71q3yUdYzgFlw==",
                    "name":"滋补药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"kUJkNgKYdWqAp11CrHhcyQ==",
                    "name":"全身用蛋白同化药物",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"4NG2M2B4kg4ZpXkT9nX94Q==",
                    "name":"刺激食欲药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"eY2mepepmHAtn0cGfRplsplsxobRTDqw==",
                    "name":"其它消化道和代谢用药",
                    "supId":"6bumiplsplsTODCneDweUyunlrg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"yriArymepepmmcVTplsplsuzfliPZ03Q==",
                            "drugName":"思美泰"
                        }
                    ]
                },
                {
                    "id":"OA5qUaPhplsplsVcakivozxgo8g==",
                    "name":"抗血栓形成药",
                    "supId":"zI5fplsplsBNzTCSKBdEwD2whEg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"vUuW4U4LTIMLt4EbvDFaJQ==",
                            "drugName":"万他维"
                        }
                    ]
                },
                {
                    "id":"GrpJzmEDv9gr095zgKdl4A==",
                    "name":"止血药",
                    "supId":"zI5fplsplsBNzTCSKBdEwD2whEg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"CKb2hE3YKvmlvOn76yKjOg==",
                    "name":"抗贫血制剂",
                    "supId":"zI5fplsplsBNzTCSKBdEwD2whEg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"chtdDVLVMRYRtMtHH4mepepmIyA==",
                            "drugName":"维生素B12注射液"
                        }
                    ]
                },
                {
                    "id":"j6NSy8dDGDrXdU3eteAyMg==",
                    "name":"血浆代用品和输注液",
                    "supId":"zI5fplsplsBNzTCSKBdEwD2whEg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"mepepmy3JLraYWmBvoKP1JYnhzw==",
                    "name":"其他血液系统用药",
                    "supId":"zI5fplsplsBNzTCSKBdEwD2whEg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"dkgtkiYSJfmepepm8SjUibmWdkg==",
                            "drugName":"麦通纳"
                        }
                    ]
                },
                {
                    "id":"laplsplsqAKAmepepmOUjITNNCpECroA==",
                    "name":"心脏病治疗用药",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"dJaepYKBKu3VMaSS3ka6xQ==",
                            "drugName":"万爽力"
                        },
                        {
                            "drugId":"kMfCBqxDVS2tM8dNR7plsplsWOg==",
                            "drugName":"凯时"
                        },
                        {
                            "drugId":"KsvkCUNJ61c7sg5RcejyRw==",
                            "drugName":"盐酸胺碘酮片"
                        },
                        {
                            "drugId":"uCrkxKfqaBCE0nTd5zJ7rQ==",
                            "drugName":"地高辛片"
                        }
                    ]
                },
                {
                    "id":"4Xvbkots5qelAbpPnUDmepepmEw==",
                    "name":"抗高血压药",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"DHiTqyplsplsLaCp1IdFOLfkPYA==",
                    "name":"利尿剂",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"DD8lNGO4MVmepepmplsplsEQUiLkK48w==",
                            "drugName":"螺内酯片"
                        }
                    ]
                },
                {
                    "id":"HrAbUzIXksNAfbatelUHqg==",
                    "name":"周围血管扩张药",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"pobr7HEYk6beWQIzFaSzdw==",
                    "name":"血管保护剂",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"hccDXgNJHE7gJiv39hyrBA==",
                            "drugName":"太宁"
                        },
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        }
                    ]
                },
                {
                    "id":"GmeJo7zLhJIqdXVjR4tiKg==",
                    "name":"β-阻滞剂",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"2biuBBvmblqfC6PyFOmepepmTYA==",
                            "drugName":"倍他乐克"
                        }
                    ]
                },
                {
                    "id":"gbQSBciofXYMcp2ue1pBgA==",
                    "name":"钙通道阻滞剂",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"zMlZk05bDnESnhe49BMqDw==",
                            "drugName":"兰迪"
                        }
                    ]
                },
                {
                    "id":"ZJhp5REUc1ndIa1IXD5UEQ==",
                    "name":"作用于肾素-血管紧张素系统的药物",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"me9z7SjfO4wN60KvSplspls1nwQ==",
                            "drugName":"代文"
                        },
                        {
                            "drugId":"0g030YIZ3DFqLtnN4Nz8Pg==",
                            "drugName":"科素亚"
                        },
                        {
                            "drugId":"TEq4vf1XPrch2S5iqtIF1Q==",
                            "drugName":"蒙诺"
                        },
                        {
                            "drugId":"dPxsf2g2GbIUOPByKsmgzA==",
                            "drugName":"雅施达"
                        }
                    ]
                },
                {
                    "id":"Yt7OHwB7M7eLdxofiFO7Ew==",
                    "name":"降血脂药",
                    "supId":"9XplsplsImepepmvfYnixfHAIs46rpmepepmg==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"PirtG58xplspls1PJpSBivAGSwA==",
                            "drugName":"舒降之"
                        }
                    ]
                },
                {
                    "id":"gpsjwrnNLjecx73k39LOQg==",
                    "name":"皮肤病用抗真菌药",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"dr5wTUfpsWlBTT4ZAh0Hpw==",
                    "name":"润肤剂和保护剂",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"0v4vB2SRiJ4CzuvVLzAC9g==",
                    "name":"创伤和溃疡治疗药",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"7dpfJZZJBwVZbkDNqmrwVg==",
                    "name":"止痒药，包括抗组织胺药、麻醉药等",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"3URVLO3TBq0WvtcIRoyvAQ==",
                            "drugName":"非那根"
                        }
                    ]
                },
                {
                    "id":"YQFRaDmepepm6AJcAEIpwyXHHzw==",
                    "name":"治疗牛皮癣药",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"N0AtXgIjea9G1KuaykjCVA==",
                    "name":"皮肤病用抗生素和化学治疗药物",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"tIsBLdHqHboMLK3plsplsOjMdeA==",
                            "drugName":"希捷"
                        },
                        {
                            "drugId":"gd8USXADlfcpjAytgvfsVQ==",
                            "drugName":"硫酸阿米卡星注射液"
                        },
                        {
                            "drugId":"ijNhveAdLPdEk4gyINwQOw==",
                            "drugName":"硫酸庆大霉素颗粒"
                        },
                        {
                            "drugId":"w4j42ixFCyz1nTGmTkP8Mw==",
                            "drugName":"土霉素片"
                        }
                    ]
                },
                {
                    "id":"43KTWYL9x4529yZ2qmwgig==",
                    "name":"皮肤病用皮质激素制剂",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        },
                        {
                            "drugId":"aOsovsqyUFiCimepepm1vbmepepmHRDA==",
                            "drugName":"吸入用布地奈德混悬液"
                        }
                    ]
                },
                {
                    "id":"YIrplsplspnGXf3YTjdSjJ3XLlg==",
                    "name":"抗菌剂和消毒剂",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"Tqrax8HHj4vinl4onxw8KQ==",
                    "name":"含药敷料",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"LsYRKqiNdX7U9r5IZUA1uQ==",
                    "name":"抗痤疮制剂",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        }
                    ]
                },
                {
                    "id":"Xs5eV4rGGX5stobI9w3O5w==",
                    "name":"其他皮肤病用制剂",
                    "supId":"rK6aqrbVZSnTMccr8ZyqRQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"qUNKppsymEc44BweJ2gplsplsgQ==",
                            "drugName":"海正麦克丁"
                        }
                    ]
                },
                {
                    "id":"RprTLrKYlVFx87xplsplsJURjSA==",
                    "name":"妇科抗感染药和抗菌剂",
                    "supId":"wLgjZt8jKiufR4H8LRQqyQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"yFKBYeDBqGCjtHBRmIHYlw==",
                            "drugName":"呋喃唑酮片"
                        },
                        {
                            "drugId":"w4j42ixFCyz1nTGmTkP8Mw==",
                            "drugName":"土霉素片"
                        }
                    ]
                },
                {
                    "id":"V4084fkAPzCrQGy3kTXOFg==",
                    "name":"其他妇科用药",
                    "supId":"wLgjZt8jKiufR4H8LRQqyQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"NWRplsplsuO0Z9YYV4pegveR5AA==",
                    "name":"性激素及生殖系统调节剂",
                    "supId":"wLgjZt8jKiufR4H8LRQqyQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"kBjhQBUFZecM4Ut1hmUngg==",
                            "drugName":"宜利治"
                        }
                    ]
                },
                {
                    "id":"oVTF6GV4nErwNzdaH4w3AA==",
                    "name":"泌尿系统药物",
                    "supId":"wLgjZt8jKiufR4H8LRQqyQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"v6ZwNsUqlsXd2PG4lLEptA==",
                            "drugName":"哈乐"
                        },
                        {
                            "drugId":"kMfCBqxDVS2tM8dNR7plsplsWOg==",
                            "drugName":"凯时"
                        },
                        {
                            "drugId":"uNqCirplsplsUQFvsrprgOE2law==",
                            "drugName":"盐酸黄酮哌酯片"
                        }
                    ]
                },
                {
                    "id":"3f7nVplsplsplsplsYuQYilMpmepepmkzekWw==",
                    "name":"垂体、下丘脑及其类似药",
                    "supId":"jF8FzxOFsBpeYZuffcdTQw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"x7untkVlN8B7sXXo76ow3A==",
                            "drugName":"善宁"
                        }
                    ]
                },
                {
                    "id":"D6wzGNGoGJUewqs8U1VxxQ==",
                    "name":"全身用皮质激素类",
                    "supId":"jF8FzxOFsBpeYZuffcdTQw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        }
                    ]
                },
                {
                    "id":"Q3fjeppoQnp8mepepmvHzhHCMhA==",
                    "name":"甲状腺药",
                    "supId":"jF8FzxOFsBpeYZuffcdTQw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"CsjLj37c6QVw48opqLdATw==",
                            "drugName":"优甲乐"
                        }
                    ]
                },
                {
                    "id":"mepepmhZkmepepmCWeuji4zLi5LWedVA==",
                    "name":"胰腺激素类",
                    "supId":"jF8FzxOFsBpeYZuffcdTQw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"0YmQMQsjY6zU6nP1OvF3PQ==",
                    "name":"钙稳态药",
                    "supId":"jF8FzxOFsBpeYZuffcdTQw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"nKl9yWI81qZAk74YOBXCXg==",
                    "name":"全身用抗细菌药",
                    "supId":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"5WtZupDQUmepepmqrXFFmZYHFwQ==",
                            "drugName":"美平"
                        },
                        {
                            "drugId":"kMurWJRsdY0UbQsZWHARMg==",
                            "drugName":"稳可信"
                        },
                        {
                            "drugId":"C8qxgUL7qpXtAIyplsplsewj28A==",
                            "drugName":"倍司特克"
                        },
                        {
                            "drugId":"LBKmepepmkzC2NRXJUk2JPYRcfA==",
                            "drugName":"美克威"
                        },
                        {
                            "drugId":"U5MObbdxJct6JvdMGqPYgQ==",
                            "drugName":"诺达明"
                        },
                        {
                            "drugId":"1n4ZlEbr17plsplsvUbFlWBpjmA==",
                            "drugName":"苏中"
                        },
                        {
                            "drugId":"KyHSLmepepma2V3QWvZvooqGZmepepmg==",
                            "drugName":"斯沃"
                        },
                        {
                            "drugId":"iko1ISmjJCwLvDhxv9JlXA==",
                            "drugName":"舒普深"
                        },
                        {
                            "drugId":"luRg30Z6g8sIFqh1TxuSaA==",
                            "drugName":"尤林加"
                        },
                        {
                            "drugId":"mepepmfNmvSspWI6Wf0qtlXe4Lg==",
                            "drugName":"健澳"
                        },
                        {
                            "drugId":"rrMU0vRgnNIhMWUEJcjgXw==",
                            "drugName":"安迪泰"
                        },
                        {
                            "drugId":"ue3YhzFW8oVi17WBue4Rdw==",
                            "drugName":"派奇"
                        },
                        {
                            "drugId":"6NBhvZrY5KBGBHyzdDdpgA==",
                            "drugName":"甲砜霉素肠溶片"
                        },
                        {
                            "drugId":"ZrnFkH10utn2hmepepmH57zmepepmdHA==",
                            "drugName":"莱得怡"
                        },
                        {
                            "drugId":"sdSrZC6b8OoJDI6SFJdZlQ==",
                            "drugName":"罗邦"
                        },
                        {
                            "drugId":"MEcfM6rDTiSURTeBv4faDA==",
                            "drugName":"拜复乐"
                        },
                        {
                            "drugId":"wKMIXOFZgALEOxfplsplsUhVOkA==",
                            "drugName":"西力欣"
                        },
                        {
                            "drugId":"7mepepmyqosigTmDJUvplsplsih025qg==",
                            "drugName":"佳美唑"
                        },
                        {
                            "drugId":"dRZKa2zP2OmwTw6VvuN5Pw==",
                            "drugName":"拜美"
                        },
                        {
                            "drugId":"b2tV49ChRInr6IlmepepmhGyd4Q==",
                            "drugName":"硫酸核糖霉素注射液"
                        },
                        {
                            "drugId":"sUPK8lhQmepepm4qFviPVuemepepmz6Q==",
                            "drugName":"罗红霉素干混悬剂"
                        },
                        {
                            "drugId":"IARfClLJZniFaJFOd2395A==",
                            "drugName":"阿莫西林胶囊"
                        },
                        {
                            "drugId":"RAdQ2YANYA6mbm0Q0nngsw==",
                            "drugName":"阿莫西林颗粒"
                        },
                        {
                            "drugId":"obYskYeALSxmepepmw7PPf98m8Q==",
                            "drugName":"安必君"
                        },
                        {
                            "drugId":"gd8USXADlfcpjAytgvfsVQ==",
                            "drugName":"硫酸阿米卡星注射液"
                        },
                        {
                            "drugId":"ijNhveAdLPdEk4gyINwQOw==",
                            "drugName":"硫酸庆大霉素颗粒"
                        },
                        {
                            "drugId":"w4j42ixFCyz1nTGmTkP8Mw==",
                            "drugName":"土霉素片"
                        }
                    ]
                },
                {
                    "id":"1lmepepm9ofmwIxQqNGtLK6FAAA==",
                    "name":"全身用抗真菌药",
                    "supId":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"Dn3heZP4jCYJw9c3nLuK6A==",
                    "name":"抗分枝杆菌药",
                    "supId":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"4mUTQwpe9NGU03JbTfjlLQ==",
                            "drugName":"胜君"
                        }
                    ]
                },
                {
                    "id":"h0nqRxm8rw6dzQqG30RUow==",
                    "name":"全身用抗病毒药",
                    "supId":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"bUxwmepepmxJKhSbm2D3SRpjplspls6g==",
                            "drugName":"恩尔欣"
                        }
                    ]
                },
                {
                    "id":"w0VJHjDQjjGmepepmDcli7royQw==",
                    "name":"免疫血清和免疫球蛋白",
                    "supId":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"bS2frXVe52q1fhNBo0IXYg==",
                    "name":"疫苗",
                    "supId":"bEAFpmepepmUrPg2EnvnXNrVoQQ==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"W0wXLapCLBwplsplsZcunULmepepmmXA==",
                    "name":"抗肿瘤药",
                    "supId":"oPYmepepmBOFKajCMeszxf2CnLA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"OFbKmYxBO7by6kYY5C3IxQ==",
                            "drugName":"匹服平"
                        },
                        {
                            "drugId":"Qrv68OAxSdmepepmfYWOplsplspEkKtg==",
                            "drugName":"爱必妥"
                        },
                        {
                            "drugId":"lDckYd2BmepepmhcJKnofGaTrTQ==",
                            "drugName":"艾诺宁"
                        },
                        {
                            "drugId":"8yx8KNwoUhyHww7KowOwZw==",
                            "drugName":"健择"
                        },
                        {
                            "drugId":"mepepmY0aAvqtLR3fGx93wW0rug==",
                            "drugName":"注射用硫酸长春新碱"
                        },
                        {
                            "drugId":"yOfNva8qyp09yPsY1plsplsbQsQ==",
                            "drugName":"恩度"
                        },
                        {
                            "drugId":"jsMQTBsigfiZiiWxjYJ5lQ==",
                            "drugName":"艾去适"
                        },
                        {
                            "drugId":"zVFz8sVdTHWrBamepepm5g9FQBg==",
                            "drugName":"安维汀"
                        },
                        {
                            "drugId":"DxBwplspls04CgViUoK3Pkuyk6Q==",
                            "drugName":"格列卫"
                        },
                        {
                            "drugId":"90mWnSg3ZBjjSiVmYAFrDw==",
                            "drugName":"万珂"
                        },
                        {
                            "drugId":"o3081LrzkQY2plsplsGTXbNJDHw==",
                            "drugName":"施达赛"
                        }
                    ]
                },
                {
                    "id":"e8Jv23z3zqyhyTO5c2WBHw==",
                    "name":"内分泌治疗用药",
                    "supId":"oPYmepepmBOFKajCMeszxf2CnLA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"kBjhQBUFZecM4Ut1hmUngg==",
                            "drugName":"宜利治"
                        }
                    ]
                },
                {
                    "id":"SG8xvpsYVZERERPplsplsmepepmr6mwg==",
                    "name":"免疫刺激剂",
                    "supId":"oPYmepepmBOFKajCMeszxf2CnLA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"9NEYwY36FKOyL2hQY9Cy1A==",
                            "drugName":"罗荛愫"
                        },
                        {
                            "drugId":"6HTdFuFM0JdbOtYwvk3nkw==",
                            "drugName":"力尔肽"
                        }
                    ]
                },
                {
                    "id":"ksbCjDBkGLKZBZ084t1DrQ==",
                    "name":"免疫抑制剂",
                    "supId":"oPYmepepmBOFKajCMeszxf2CnLA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"C2nBO0tY8cplsplsJ3plspls9XZnG1QQ==",
                    "name":"抗炎药和抗风湿药",
                    "supId":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"a4rZO81dl0aNG8uunrplsplstEQ==",
                            "drugName":"迪可安"
                        },
                        {
                            "drugId":"BNPVX28CNEjwF6N2lxC0HA==",
                            "drugName":"芬布芬片"
                        }
                    ]
                },
                {
                    "id":"p8JZe9jYYvK4Hem0t46zzg==",
                    "name":"关节和肌肉痛的局部用药",
                    "supId":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"a4rZO81dl0aNG8uunrplsplstEQ==",
                            "drugName":"迪可安"
                        }
                    ]
                },
                {
                    "id":"0w1YQfCERXmepepm6jy8i0DhGxA==",
                    "name":"肌肉松弛药",
                    "supId":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"48ELqoiXwZvPNiMSIcEf3A==",
                    "name":"抗痛风制剂",
                    "supId":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"APqDsNpf5oi5pIjpq8sATQ==",
                    "name":"治疗骨骼疾病的药物",
                    "supId":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"NWhD4vbOYGEtPmepepm8y97eyeg==",
                    "name":"其它肌肉-骨骼系统疾病用药",
                    "supId":"VNtMzgk5WmWmoZOplsplsTdfpWw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"phnbNnX0iFssjc9l1LBQHA==",
                    "name":"麻醉剂",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"cAdmepepmq7podOcYUlRn4dmbHg==",
                            "drugName":"得普利麻"
                        },
                        {
                            "drugId":"P10Q1Xn7JfvYLOKJxcdlUg==",
                            "drugName":"普鲁卡因肾上腺素注射液"
                        }
                    ]
                },
                {
                    "id":"ZElTihvmGoFkx9ElBKplspls9Ww==",
                    "name":"止痛药",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"plsplsQJ5i16Qv1y3XmepepmXu5zWQyw==",
                    "name":"抗癫痫药",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"6hmepepmMbPbplsplsDVBm3MaFYxy56Q==",
                            "drugName":"乐瑞卡"
                        }
                    ]
                },
                {
                    "id":"08BkWjYaPJRjuVyEhAXwZw==",
                    "name":"抗帕金森氏病药",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"00m1LihYNVplsplsc4cyn7NwjoA==",
                    "name":"精神安定药",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"fy4PK0scBK9Vqe7HplsplsmepepmeWBg==",
                            "drugName":"力月西"
                        },
                        {
                            "drugId":"xCbBIhWUa9vApmepepmcqf12aWA==",
                            "drugName":"再普乐"
                        },
                        {
                            "drugId":"YEWplsplsplsplswhkqmepepm9OWgz5ZtuEGA==",
                            "drugName":"黛力新"
                        },
                        {
                            "drugId":"TZXffpzpgVUuKYVPLfwHYw==",
                            "drugName":"善思达"
                        }
                    ]
                },
                {
                    "id":"P4PG8uyFwtphQ8kUbaplsplsWUQ==",
                    "name":"精神兴奋药",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"2I5bImPKaRbTjDxEfUmepepmQPA==",
                            "drugName":"倍清星"
                        },
                        {
                            "drugId":"YEWplsplsplsplswhkqmepepm9OWgz5ZtuEGA==",
                            "drugName":"黛力新"
                        }
                    ]
                },
                {
                    "id":"vmepepmsWk2AGjIplspls9CDeyMBAmHQ==",
                    "name":"其它神经系统药物",
                    "supId":"cweGrppsikeakKQ0eNplsplsmDA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"gT08E7pQXpekD4K0QuoHeg==",
                            "drugName":"敏使朗"
                        },
                        {
                            "drugId":"OlPl37VZjcj7c0jedmepepmX2iQ==",
                            "drugName":"西比灵"
                        },
                        {
                            "drugId":"x6SpcF2NZzeWb1QMkydCXA==",
                            "drugName":"必存"
                        }
                    ]
                },
                {
                    "id":"zjIGiSJ9ajB5eSHSjC511w==",
                    "name":"抗原虫药",
                    "supId":"N5OXRZbGzWRAK7BdPwsaWw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"d6Koscj9wjksL2plsplswojzNzQ==",
                            "drugName":"安立康"
                        },
                        {
                            "drugId":"olvmHCct5vu7plsplsoSIg5JBAA==",
                            "drugName":"科泰复"
                        }
                    ]
                },
                {
                    "id":"IOugYuSmepepm6IsDrrSq2Mtzkw==",
                    "name":"驱蠕虫药",
                    "supId":"N5OXRZbGzWRAK7BdPwsaWw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"qUNKppsymEc44BweJ2gplsplsgQ==",
                            "drugName":"海正麦克丁"
                        },
                        {
                            "drugId":"X6tith0MmepepmWhvDrIZlmepepmA58g==",
                            "drugName":"史克肠虫清"
                        }
                    ]
                },
                {
                    "id":"TfHIOTPwmAir5UaWpHbX3Q==",
                    "name":"杀体外寄生虫药（包括杀疥虫药、杀虫剂及驱虫剂",
                    "supId":"N5OXRZbGzWRAK7BdPwsaWw==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"u7W6fOWmepepmi9e7OlzVLSE2gQ==",
                    "name":"鼻用制剂",
                    "supId":"Z6gvDdWkMY3JCRh554wMAA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        },
                        {
                            "drugId":"aOsovsqyUFiCimepepm1vbmepepmHRDA==",
                            "drugName":"吸入用布地奈德混悬液"
                        }
                    ]
                },
                {
                    "id":"uVcR5zjplsplsdmepepmjdPMvRTX6IvQ==",
                    "name":"咽喉用制剂",
                    "supId":"Z6gvDdWkMY3JCRh554wMAA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"rDP8DJ5OAqPGwEJC6kivRw==",
                    "name":"抗哮喘药",
                    "supId":"Z6gvDdWkMY3JCRh554wMAA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"jbDTytP27rzAZm5sCfmoig==",
                            "drugName":"万托林"
                        },
                        {
                            "drugId":"Qhwc0DccmXMLbkuFD4fUmepepmg==",
                            "drugName":"氨茶碱注射液"
                        },
                        {
                            "drugId":"lRjsBrYOCcplspls9iylicKV16Q==",
                            "drugName":"舒利迭"
                        },
                        {
                            "drugId":"PcBqavpgyAvXLsFNcWZnPQ==",
                            "drugName":"苏顺"
                        },
                        {
                            "drugId":"aOsovsqyUFiCimepepm1vbmepepmHRDA==",
                            "drugName":"吸入用布地奈德混悬液"
                        }
                    ]
                },
                {
                    "id":"wLOm8qHse3dJO4GHOQFyplsplsQ==",
                    "name":"咳嗽和感冒用药",
                    "supId":"Z6gvDdWkMY3JCRh554wMAA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"r4LlFTfJ7MD2oBpYQjAkPQ==",
                    "name":"全身用抗组胺药",
                    "supId":"Z6gvDdWkMY3JCRh554wMAA==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"3URVLO3TBq0WvtcIRoyvAQ==",
                            "drugName":"非那根"
                        },
                        {
                            "drugId":"kZ1854Hsq7OWMNPj2ahGoA==",
                            "drugName":"史泰舒"
                        }
                    ]
                },
                {
                    "id":"yz21FruQyEmepepm6o6plsplsplsplsVbmepepmREA==",
                    "name":"其它呼吸系统制剂",
                    "supId":"Z6gvDdWkMY3JCRh554wMAA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"irF7CHaPMrXtqrlZU0rMxQ==",
                    "name":"眼科用药",
                    "supId":"44ORHNfUVssuau8plsplsS0qVFw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"ue3YhzFW8oVi17WBue4Rdw==",
                            "drugName":"派奇"
                        },
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        },
                        {
                            "drugId":"MEcfM6rDTiSURTeBv4faDA==",
                            "drugName":"拜复乐"
                        },
                        {
                            "drugId":"wKMIXOFZgALEOxfplsplsUhVOkA==",
                            "drugName":"西力欣"
                        },
                        {
                            "drugId":"obYskYeALSxmepepmw7PPf98m8Q==",
                            "drugName":"安必君"
                        },
                        {
                            "drugId":"gd8USXADlfcpjAytgvfsVQ==",
                            "drugName":"硫酸阿米卡星注射液"
                        },
                        {
                            "drugId":"ijNhveAdLPdEk4gyINwQOw==",
                            "drugName":"硫酸庆大霉素颗粒"
                        },
                        {
                            "drugId":"w4j42ixFCyz1nTGmTkP8Mw==",
                            "drugName":"土霉素片"
                        }
                    ]
                },
                {
                    "id":"alTmepepmGVplsplsr31aXSEpwHjAe5Q==",
                    "name":"耳科用药",
                    "supId":"44ORHNfUVssuau8plsplsS0qVFw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        },
                        {
                            "drugId":"ijNhveAdLPdEk4gyINwQOw==",
                            "drugName":"硫酸庆大霉素颗粒"
                        }
                    ]
                },
                {
                    "id":"gsWsuxwtfWDVNps7o6DXMQ==",
                    "name":"眼科和耳科用药",
                    "supId":"44ORHNfUVssuau8plsplsS0qVFw==",
                    "position":null,
                    "recommendDrugs":[
                        {
                            "drugId":"o1ls0NrTiVy4W0S3ZLN1rQ==",
                            "drugName":"息洛安"
                        },
                        {
                            "drugId":"ijNhveAdLPdEk4gyINwQOw==",
                            "drugName":"硫酸庆大霉素颗粒"
                        }
                    ]
                },
                {
                    "id":"aIRVKEVf1YOLOlAXQ09Yzw==",
                    "name":"过敏原",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"t7jgJd3mepepmuqtizsRaAoKL7w==",
                    "name":"所有其它治疗用产品",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"MuosAGCmepepmLW3OiOvKFxz59g==",
                    "name":"诊断用药",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"ZCYZLplsplsQUaC23YVZzykwQQA==",
                    "name":"一般营养品",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"nMCgKR3qQFda2z37TBYbIQ==",
                    "name":"所有其他非治疗用制品",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"oWACqTPVICD6FewT9tOiwA==",
                    "name":"造影剂",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"JdvLKqLRnLbJVGTqg6MnGA==",
                    "name":"诊断用放射性药物",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"yarrLQuRatk1dDer1uBCyQ==",
                    "name":"治疗用放射性药物",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                },
                {
                    "id":"0T2Hyma47PcxkUwXXcbBdg==",
                    "name":"外科敷料",
                    "supId":"EYXgNJYbplsplsC2lms4M0Si2plsplsA==",
                    "position":null,
                    "recommendDrugs":null
                }
            ]
        }'''